"""YouTube auth helpers for cloud deployments (cookies + HTTP proxy).

Render/Vercel datacenter IPs are blocked by YouTube (403 / LOGIN_REQUIRED).
Set either:
  - YOUTUBE_COOKIES  → Netscape cookies.txt contents (from your browser), or
  - YOUTUBE_HTTP_PROXY → residential/mobile HTTP(S) proxy URL
"""

from __future__ import annotations

from pathlib import Path

from app.config import settings

_COOKIE_FILE: Path | None = None


def youtube_proxy_url() -> str | None:
    raw = (settings.youtube_http_proxy or "").strip()
    return raw or None


def youtube_cookie_header() -> str | None:
    """Build Cookie header from Netscape cookies env / file."""
    path = ensure_youtube_cookie_file()
    if not path:
        return None
    pairs: list[str] = []
    for line in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) >= 7:
            name, value = parts[5], parts[6]
            if name:
                pairs.append(f"{name}={value}")
        elif "=" in line and not line.startswith("http"):
            # allow simple name=value lines
            pairs.append(line)
    return "; ".join(pairs) if pairs else None


def clear_youtube_cookie_cache() -> None:
    global _COOKIE_FILE
    _COOKIE_FILE = None


def install_youtube_cookies(text: str) -> Path:
    """Write Netscape cookies to durable data dir and refresh cache."""
    clear_youtube_cookie_cache()
    cleaned = (text or "").strip().replace("\\n", "\n")
    if not cleaned:
        raise ValueError("Empty cookies")
    if "Netscape" not in cleaned and "\t" not in cleaned and "=" in cleaned:
        lines = ["# Netscape HTTP Cookie File", "# Generated by Nexora"]
        for part in cleaned.split(";"):
            part = part.strip()
            if "=" not in part:
                continue
            name, value = part.split("=", 1)
            lines.append(
                "\t".join(
                    [
                        ".youtube.com",
                        "TRUE",
                        "/",
                        "TRUE",
                        "2147483647",
                        name.strip(),
                        value.strip(),
                    ]
                )
            )
        cleaned = "\n".join(lines) + "\n"
    out = settings.data_dir / "youtube.cookies.txt"
    out.write_text(cleaned if cleaned.endswith("\n") else cleaned + "\n", encoding="utf-8")
    global _COOKIE_FILE
    _COOKIE_FILE = out
    return out


def ensure_youtube_cookie_file() -> Path | None:
    """Persist YOUTUBE_COOKIES env into a Netscape cookies file for yt-dlp."""
    global _COOKIE_FILE
    if _COOKIE_FILE and _COOKIE_FILE.exists():
        return _COOKIE_FILE

    raw = (settings.youtube_cookies or "").strip()
    file_setting = (settings.youtube_cookies_file or "").strip()
    if file_setting:
        p = Path(file_setting)
        if p.exists() and p.stat().st_size > 0:
            _COOKIE_FILE = p
            return p

    # Durable file installed via /api/admin/youtube-cookies (Render disk)
    durable = settings.data_dir / "youtube.cookies.txt"
    if durable.exists() and durable.stat().st_size > 0:
        _COOKIE_FILE = durable
        return durable

    if not raw:
        return None

    # Support env with escaped newlines
    text = raw.replace("\\n", "\n")
    if "Netscape" not in text and "\t" not in text:
        # wrap bare cookie header into a minimal netscape-ish file for yt-dlp
        lines = ["# Netscape HTTP Cookie File", "# Generated by Nexora"]
        for part in text.split(";"):
            part = part.strip()
            if "=" not in part:
                continue
            name, value = part.split("=", 1)
            lines.append(
                "\t".join(
                    [
                        ".youtube.com",
                        "TRUE",
                        "/",
                        "TRUE",
                        "2147483647",
                        name.strip(),
                        value.strip(),
                    ]
                )
            )
        text = "\n".join(lines) + "\n"

    out = settings.data_dir / "youtube.cookies.txt"
    out.write_text(text, encoding="utf-8")
    _COOKIE_FILE = out
    return out


def youtube_auth_status() -> dict:
    cookies = bool(ensure_youtube_cookie_file())
    proxy = bool(youtube_proxy_url())
    return {
        "cookies_configured": cookies,
        "proxy_configured": proxy,
        "cloud_youtube_ready": cookies or proxy,
        "download_fallback": bool(settings.youtube_download_fallback) or cookies,
    }


def httpx_client_kwargs() -> dict:
    """Common httpx kwargs with optional proxy + cookie header."""
    headers = {
        "User-Agent": (
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
            "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
        ),
        "Accept-Language": "en-US,en;q=0.9",
    }
    cookie = youtube_cookie_header()
    if cookie:
        headers["Cookie"] = cookie
    kwargs: dict = {
        "timeout": 45.0,
        "follow_redirects": True,
        "headers": headers,
    }
    proxy = youtube_proxy_url()
    if proxy:
        kwargs["proxy"] = proxy
    return kwargs
