"""YouTube auth helpers for cloud deployments (cookies + HTTP proxy).

Render/Vercel datacenter IPs are blocked by YouTube (403 / LOGIN_REQUIRED).
Set either:
  - YOUTUBE_COOKIES  → Netscape cookies.txt contents (from your browser), or
  - YOUTUBE_HTTP_PROXY → residential/mobile HTTP(S) proxy URL
"""

from __future__ import annotations

from pathlib import Path

from app.config import settings

_COOKIE_FILE: Path | None = None

# InnerTube rejects oversized Cookie headers (HTTP 413). Keep only session markers.
_AUTH_COOKIE_NAMES = frozenset(
    {
        "LOGIN_INFO",
        "SID",
        "HSID",
        "SSID",
        "APISID",
        "SAPISID",
        "__Secure-1PSID",
        "__Secure-3PSID",
        "__Secure-1PSIDTS",
        "__Secure-3PSIDTS",
        "__Secure-1PAPISID",
        "__Secure-3PAPISID",
        "__Secure-1PSIDCC",
        "__Secure-3PSIDCC",
        "PREF",
        "CONSENT",
        "VISITOR_INFO1_LIVE",
        "YSC",
        "SESSION_TOKEN",
    }
)


def youtube_proxy_url() -> str | None:
    raw = (settings.youtube_http_proxy or "").strip()
    return raw or None


def _iter_netscape_rows(path: Path):
    for line in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        raw = line.strip()
        if not raw or raw.startswith("#"):
            continue
        parts = raw.split("\t")
        if len(parts) >= 7 and parts[5]:
            yield parts[0], parts[5], parts[6], raw
        elif "=" in raw and not raw.startswith("http"):
            name, value = raw.split("=", 1)
            yield ".youtube.com", name.strip(), value.strip(), raw


def _is_auth_cookie(name: str) -> bool:
    return name in _AUTH_COOKIE_NAMES or name.startswith("__Secure-")


def youtube_cookie_header() -> str | None:
    """Slim Cookie header — full exports blow past YouTube's request limit (413)."""
    path = ensure_youtube_cookie_file()
    if not path:
        return None
    # name -> (score, value); prefer youtube.com over google.com
    best: dict[str, tuple[tuple[int, int], str]] = {}
    for domain, name, value, _raw in _iter_netscape_rows(path):
        host = domain.lower().lstrip(".")
        if "youtube.com" not in host and "google.com" not in host:
            continue
        if not _is_auth_cookie(name):
            continue
        score = (2 if "youtube.com" in host else 1, len(host))
        prev = best.get(name)
        if prev is None or score > prev[0]:
            best[name] = (score, value)
    if not best:
        return None
    return "; ".join(f"{name}={val}" for name, (_s, val) in best.items())


def clear_youtube_cookie_cache() -> None:
    global _COOKIE_FILE
    _COOKIE_FILE = None


def install_youtube_cookies(text: str) -> Path:
    """Write Netscape cookies to durable data dir and refresh cache."""
    clear_youtube_cookie_cache()
    cleaned = (text or "").strip().replace("\\n", "\n")
    if not cleaned:
        raise ValueError("Empty cookies")
    if "Netscape" not in cleaned and "\t" not in cleaned and "=" in cleaned:
        lines = ["# Netscape HTTP Cookie File", "# Generated by Nexora"]
        for part in cleaned.split(";"):
            part = part.strip()
            if "=" not in part:
                continue
            name, value = part.split("=", 1)
            lines.append(
                "\t".join(
                    [
                        ".youtube.com",
                        "TRUE",
                        "/",
                        "TRUE",
                        "2147483647",
                        name.strip(),
                        value.strip(),
                    ]
                )
            )
        cleaned = "\n".join(lines) + "\n"
    out = settings.data_dir / "youtube.cookies.txt"
    out.write_text(cleaned if cleaned.endswith("\n") else cleaned + "\n", encoding="utf-8")
    global _COOKIE_FILE
    _COOKIE_FILE = out
    return out


def ensure_youtube_cookie_file() -> Path | None:
    """Persist YOUTUBE_COOKIES env into a Netscape cookies file for yt-dlp."""
    global _COOKIE_FILE
    if _COOKIE_FILE and _COOKIE_FILE.exists():
        return _COOKIE_FILE

    raw = (settings.youtube_cookies or "").strip()
    file_setting = (settings.youtube_cookies_file or "").strip()
    if file_setting:
        p = Path(file_setting)
        if p.exists() and p.stat().st_size > 0:
            _COOKIE_FILE = p
            return p

    # Durable file installed via /api/admin/youtube-cookies (Render disk)
    durable = settings.data_dir / "youtube.cookies.txt"
    if durable.exists() and durable.stat().st_size > 0:
        _COOKIE_FILE = durable
        return durable

    if not raw:
        return None

    # Support env with escaped newlines
    text = raw.replace("\\n", "\n")
    if "Netscape" not in text and "\t" not in text:
        # wrap bare cookie header into a minimal netscape-ish file for yt-dlp
        lines = ["# Netscape HTTP Cookie File", "# Generated by Nexora"]
        for part in text.split(";"):
            part = part.strip()
            if "=" not in part:
                continue
            name, value = part.split("=", 1)
            lines.append(
                "\t".join(
                    [
                        ".youtube.com",
                        "TRUE",
                        "/",
                        "TRUE",
                        "2147483647",
                        name.strip(),
                        value.strip(),
                    ]
                )
            )
        text = "\n".join(lines) + "\n"

    out = settings.data_dir / "youtube.cookies.txt"
    out.write_text(text, encoding="utf-8")
    _COOKIE_FILE = out
    return out


def _cookies_look_authenticated(path: Path | None) -> bool:
    """Visitor-only cookies still get 403 on cloud IPs; need a real session."""
    if not path or not path.exists():
        return False
    text = path.read_text(encoding="utf-8", errors="ignore")
    markers = (
        "\tSID\t",
        "\tLOGIN_INFO\t",
        "\tSAPISID\t",
        "\t__Secure-1PSID\t",
        "\t__Secure-3PSID\t",
        "\tSSID\t",
    )
    return any(m in text for m in markers)


def youtube_auth_status() -> dict:
    path = ensure_youtube_cookie_file()
    cookies = bool(path)
    authed = _cookies_look_authenticated(path)
    proxy = bool(youtube_proxy_url())
    return {
        "cookies_configured": cookies,
        "cookies_authenticated": authed,
        "proxy_configured": proxy,
        # Ready only when proxy or real logged-in session cookies exist.
        "cloud_youtube_ready": proxy or authed,
        "download_fallback": bool(settings.youtube_download_fallback) or authed,
    }


def httpx_client_kwargs() -> dict:
    """Common httpx kwargs with optional proxy + cookie header."""
    headers = {
        "User-Agent": (
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
            "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
        ),
        "Accept-Language": "en-US,en;q=0.9",
    }
    cookie = youtube_cookie_header()
    if cookie:
        headers["Cookie"] = cookie
    kwargs: dict = {
        "timeout": 45.0,
        "follow_redirects": True,
        "headers": headers,
    }
    proxy = youtube_proxy_url()
    if proxy:
        kwargs["proxy"] = proxy
    return kwargs
